spring.application.name=SpotifyBackendNew

# Info for spotify oauth2
spring.security.oauth2.client.provider.spotify.authorization-uri=https://accounts.spotify.com/authorize
spring.security.oauth2.client.provider.spotify.token-uri=https://accounts.spotify.com/api/token
spring.security.oauth2.client.provider.spotify.user-info-uri=https://api.spotify.com/v1/me
spring.security.oauth2.client.provider.spotify.userNameAttribute=id

# 1. Basic registration for users (without player access)
spring.security.oauth2.client.registration.spotify.client-id=${SPOTIFY_CLIENT_ID}
spring.security.oauth2.client.registration.spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
spring.security.oauth2.client.registration.spotify.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spotify.scope=user-read-private,playlist-read-private
spring.security.oauth2.client.registration.spotify.redirect-uri=http://127.0.0.1:8080/login/oauth2/code/spotify

# 2. Registration for hosts (with player access)
spring.security.oauth2.client.registration.spotify-host.provider=spotify
spring.security.oauth2.client.registration.spotify-host.client-id=${SPOTIFY_CLIENT_ID}
spring.security.oauth2.client.registration.spotify-host.client-secret=${SPOTIFY_CLIENT_SECRET}
spring.security.oauth2.client.registration.spotify-host.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spotify-host.scope=user-read-private,playlist-read-private,streaming,user-read-email,user-modify-playback-state,user-read-playback-state
spring.security.oauth2.client.registration.spotify-host.redirect-uri=http://127.0.0.1:8080/login/oauth2/code/spotify

server.servlet.session.timeout=120m